from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Glob)
admin.site.register(Continent)
admin.site.register(Country)
admin.site.register(State)
admin.site.register(District)
admin.site.register(Taluka)
admin.site.register(CityVillage)
admin.site.register(Ward)
# admin.site.register(Society)
# admin.site.register(Block)
# admin.site.register(Floor)
# admin.site.register(Houses)


admin.site.register(Religion)
admin.site.register(Sampraday)
admin.site.register(Panth)
admin.site.register(Varna)
admin.site.register(Caste)
admin.site.register(SubCaste)
admin.site.register(Gotra)
admin.site.register(SubGotra)
admin.site.register(Kul)
admin.site.register(Family)
admin.site.register(Pidhi)


admin.site.register(Section)
admin.site.register(Class)
admin.site.register(ProfCategory)
admin.site.register(ProfSubCategory)
admin.site.register(Type)
admin.site.register(Brand)
admin.site.register(PostModel)
admin.site.register(Sector)
admin.site.register(SubSector)
admin.site.register(Department)
admin.site.register(SubDepartment)
admin.site.register(RoomFlash)
admin.site.register(ModelName)
admin.site.register(ModelAccess)
admin.site.register(RecordRule)

admin.site.register(Designation)
admin.site.register(RelationType)
# admin.site.register(PermissionModule)
# admin.site.register(PermissionAction)